apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ykoenccbr-python 
  janus-idp.io/tekton: ykoenccbr-python
  backstage.io/kubernetes-id: ykoenccbr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ykoenccbr-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml