apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ykoenccbr-python
  janus-idp.io/tekton: ykoenccbr-python
  backstage.io/kubernetes-id: ykoenccbr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ykoenccbr-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
